default:
  http_metas:
    content-type: text/html

  metas:
    title:        Metafilter comments vs. Youtube comments
    robots:       index, follow
    description:  Compares the comments of Metafilter to Youtube
    keywords:     metafilter, youtube, comments
    language:     en

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
